package CIS3334.deckbuilder;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * Card class holds the data generated by the Pokemon TCG API
 * Implements serializable so data can be passed along in intents
 */
@Entity
public class Card implements Serializable {

    //unqiue key generation required for the Room database
    @PrimaryKey (autoGenerate = true)
    public Integer dbId;

    //This is the id that the API uses to identify each card
    private String id;
    private String rarity;
    private String name;
    private ArrayList<String> types;
    public Images images;
    private String supertype;
    private Set set;

    /**
     * Card object constructor
     * @param id card ID generated by the Pokemon API
     * @param rarity card rarity
     * @param name card name
     * @param types arraylist of the pokemon types classifications
     * @param images image object with image urls
     * @param supertype card's supertype classification
     * @param set set object the card belongs to
     */
    public Card(String id, String rarity, String name, ArrayList<String> types, Images images, String supertype, Set set){
        this.id = id;
        this.rarity = rarity;
        this.name = name;
        this.types = types;
        this.images = images;
        this.supertype = supertype;
        this.set = set;
    }

    /**
     * Class to retrieve name of the card
     * @return string of card name
     */
    public String getName() {
        return name;
    }

    /**
     * Class to retrieve the ID provided for the card by the API
     * @return string of card ID
     */
    public String getId() {
        return id;
    }

    /**
     * Class to retrieve rarity of the card
     * @return string of card rarity
     */
    public String getRarity() { return rarity; }

    /**
     * Class to retrieve the list of types as a single string
     * @return string of all types
     */
    public String getTypesString() {
        String allTypes = "";
        for(String type : types) {
            allTypes += type + "\n";
        }
        return allTypes;
    }

    /**
     * Class to retrieve the types as an arraylist
     * @return arraylist of all types
     */
    public ArrayList<String> getTypes() { return types; }

    /**
     * Class to retrieve the images object
     * @return images object
     */
    public Images getImages() {
        return images;
    }

    /**
     * Class to retrieve the supertype of the Pokemon
     * @return string of supertype
     */
    public String getSupertype() { return supertype; }

    /**
     * Class to retrieve the set the card belongs to
     * @return set object
     */
    public Set getSet() { return set; }

}
